// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2uZXCXEmkmO8Bs_ERs_JiLs9csMaxgKI',
    appId: '1:1081354023136:web:e91548304952550546e085',
    messagingSenderId: '1081354023136',
    projectId: 'utavine-app',
    authDomain: 'utavine-app.firebaseapp.com',
    storageBucket: 'utavine-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbquWDN4mfKeFrgIkuK83dLnws7HhvUrA',
    appId: '1:1081354023136:android:332462b35e8b765c46e085',
    messagingSenderId: '1081354023136',
    projectId: 'utavine-app',
    storageBucket: 'utavine-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7nGdzR_qdGjVxPejwuwScWUfcmkpcvgc',
    appId: '1:1081354023136:ios:d09d6ab2852ba2ee46e085',
    messagingSenderId: '1081354023136',
    projectId: 'utavine-app',
    storageBucket: 'utavine-app.firebasestorage.app',
    iosBundleId: 'com.example.utavine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7nGdzR_qdGjVxPejwuwScWUfcmkpcvgc',
    appId: '1:1081354023136:ios:d09d6ab2852ba2ee46e085',
    messagingSenderId: '1081354023136',
    projectId: 'utavine-app',
    storageBucket: 'utavine-app.firebasestorage.app',
    iosBundleId: 'com.example.utavine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2uZXCXEmkmO8Bs_ERs_JiLs9csMaxgKI',
    appId: '1:1081354023136:web:a0608ba4893feb2b46e085',
    messagingSenderId: '1081354023136',
    projectId: 'utavine-app',
    authDomain: 'utavine-app.firebaseapp.com',
    storageBucket: 'utavine-app.firebasestorage.app',
  );
}
